{{- if .Values.examples.enabled }}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mangodbs.mangodb.com
  labels:
    kube-bind.io/exported: "true"
spec:
  group: mangodb.com
  names:
    kind: MangoDB
    listKind: MangoDBList
    plural: mangodbs
    singular: mangodb
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              tier:
                type: string
                enum:
                - Dedicated
                - Shared
                default: Shared
          status:
            type: object
            properties:
              phase:
                type: string
        required:
        - spec
    subresources:
      status: {}
---
apiVersion: kube-bind.io/v1alpha2
kind: APIServiceExportTemplate
metadata:
  name: mangodb
spec:
  scope: Namespaced
  resources:
  - group: mangodb.com
    versions: 
    - v1alpha1  
    resource: mangodbs
  permissionClaims:
  - group: ""
    resource: "secrets"
    selector:
      labelSelector:
        matchLabels:
          app: "mangodb"
      namedResources:
      - name: "mangodb-credentials"
        namespace: "mangodb-namespace"
  namespaces:
  - name: mangodb-namespace
{{- end }}