apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-bind.fullname" . }}
  labels:
    {{- include "kube-bind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.backend.tls.enabled }}
    - port: {{ .Values.service.httpsPort | default 8443 }}
      targetPort: https
      protocol: TCP
      name: https
      {{- if and (eq .Values.service.type "NodePort") .Values.service.httpsNodePort }}
      nodePort: {{ .Values.service.httpsNodePort }}
      {{- end }}
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "kube-bind.selectorLabels" . | nindent 4 }}
