apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cowboys.wildwest.dev
  labels:
    kube-bind.io/exported: "true"
spec:
  group: wildwest.dev
  names:
    kind: Cowboy
    listKind: CowboyList
    plural: cowboys
    singular: cowboy
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: Cowboy is part of the wild west
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CowboySpec holds the desired state of the Cowboy.
            type: object
            properties:
              intent:
                type: string
              secretRefs:
                type: array
                description: "Array of references to Secrets containing cowboy credentials"
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: "Name of the referenced Secret"
                  required:
                  - name
          status:
            description: CowboyStatus communicates the observed state of the Cowboy.
            type: object
            properties:
              result:
                type: string
    subresources:
      status: {}