apiVersion: kube-bind.io/v1alpha2
kind: APIServiceExportTemplate
metadata:
  name: cowboys
spec:
  scope: Namespaced
  resources:
  - group: wildwest.dev
    versions: 
    - v1alpha1
    resource: cowboys
  permissionClaims:
  - group: ""
    resource: secrets
    selector:
      labelSelector:
        matchLabels:
          app: cowboy
  namespaces:
  - name: wild-west

