apiVersion: kube-bind.io/v1alpha2
kind: APIServiceExportTemplate
metadata:
  name: sheriffs
spec:
  scope: Cluster
  resources:
  - group: wildwest.dev
    versions: 
    - v1alpha1
    resource: sheriffs
  permissionClaims:
  - group: ""
    resource: secrets
    selector:
      labelSelector:
        matchLabels:
          app: sheriff
      references:
        - resource: sheriffs
          group: wildwest.dev
          jsonPath:
            name: spec.secretRefs.#.name
            namespace: spec.secretRefs.#.namespace