apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  creationTimestamp: null
  name: kube-bind.io
spec:
  permissionClaims:
  - group: rbac.authorization.k8s.io
    resource: clusterrolebindings
    verbs:
    - '*'
  - group: rbac.authorization.k8s.io
    resource: clusterroles
    verbs:
    - '*'
  - group: rbac.authorization.k8s.io
    resource: roles
    verbs:
    - '*'
  - group: rbac.authorization.k8s.io
    resource: rolebindings
    verbs:
    - '*'
  - resource: serviceaccounts
    verbs:
    - '*'
  - resource: configmaps
    verbs:
    - '*'
  - resource: secrets
    verbs:
    - '*'
  - resource: namespaces
    verbs:
    - '*'
  - group: apiextensions.k8s.io
    resource: customresourcedefinitions
    verbs:
    - '*'
  - group: apis.kcp.io
    resource: apiresourceschemas
    verbs:
    - '*'
  resources:
  - group: kube-bind.io
    name: apiconversions
    schema: v250809-5ed76a1.apiconversions.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: apiservicebindings
    schema: v251112-503d98b.apiservicebindings.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: apiserviceexportrequests
    schema: v251112-503d98b.apiserviceexportrequests.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: apiserviceexports
    schema: v251112-503d98b.apiserviceexports.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: apiserviceexporttemplates
    schema: v251112-503d98b.apiserviceexporttemplates.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: apiservicenamespaces
    schema: v250809-5ed76a1.apiservicenamespaces.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: bindableresourcesrequests
    schema: v251029-ff0a399.bindableresourcesrequests.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: boundschemas
    schema: v251106-640871f.boundschemas.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: clusterbindings
    schema: v250925-56669b8.clusterbindings.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: collections
    schema: v251106-640871f.collections.kube-bind.io
    storage:
      crd: {}
status: {}
