apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: kube-bind.io
spec:
  permissionClaims:
  - group: rbac.authorization.k8s.io
    resource: clusterrolebindings
    verbs:
    - '*'
  - group: rbac.authorization.k8s.io
    resource: clusterroles
    verbs:
    - '*'
  - group: rbac.authorization.k8s.io
    resource: roles
    verbs:
    - '*'
  - group: rbac.authorization.k8s.io
    resource: rolebindings
    verbs:
    - '*'
  - resource: serviceaccounts
    verbs:
    - '*'
  - resource: configmaps
    verbs:
    - '*'
  - resource: secrets
    verbs:
    - '*'
  - group: authorization.k8s.io
    resource: subjectaccessreviews
    verbs:
    - '*'
  - resource: namespaces
    verbs:
    - '*'
  - group: apiextensions.k8s.io
    resource: customresourcedefinitions
    verbs:
    - '*'
  - group: apis.kcp.io
    resource: apiresourceschemas
    verbs:
    - '*'
  resources:
  - group: kube-bind.io
    name: apiconversions
    schema: v250809-5ed76a1.apiconversions.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: apiservicebindingbundles
    schema: v260122-c9f0f376.apiservicebindingbundles.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: apiservicebindings
    schema: v260122-c9f0f376.apiservicebindings.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: apiserviceexportrequests
    schema: v260209-099939a.apiserviceexportrequests.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: apiserviceexports
    schema: v260119-2e5a3e93.apiserviceexports.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: apiserviceexporttemplates
    schema: v260209-099939a.apiserviceexporttemplates.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: apiservicenamespaces
    schema: v250809-5ed76a1.apiservicenamespaces.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: bindableresourcesrequests
    schema: v260122-c9f0f376.bindableresourcesrequests.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: boundschemas
    schema: v251106-640871f.boundschemas.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: clusterbindings
    schema: v260122-c9f0f376.clusterbindings.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: clusters
    schema: v251215-7d342944.clusters.kube-bind.io
    storage:
      crd: {}
  - group: kube-bind.io
    name: collections
    schema: v251106-640871f.collections.kube-bind.io
    storage:
      crd: {}
status: {}
