apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  name: v251224-24568872.bindableresourcesrequests.kube-bind.io
spec:
  group: kube-bind.io
  names:
    kind: BindableResourcesRequest
    listKind: BindableResourcesRequestList
    plural: bindableresourcesrequests
    singular: bindableresourcesrequest
  scope: Namespaced
  versions:
  - name: v1alpha2
    schema:
      description: |-
        BindableResourcesRequest is sent by the consumer to the service provider
        to indicate which resources the user wants to bind to. It is sent after
        authentication and resource selection on the service provider website.
      properties:
        apiVersion:
          description: |-
            APIVersion defines the versioned schema of this representation of an object.
            Servers should convert recognized schemas to the latest internal value, and
            may reject unrecognized values.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
          type: string
        clusterIdentity:
          description: |-
            ClusterIdentity contains information that uniquely identifies the cluster.
            When doing dry run, we expect the client to fill this field in (or it will be taken from local cluster where context is available).
          properties:
            identity:
              description: Identity is the unique identifier of the cluster.
              type: string
          type: object
        kind:
          description: |-
            Kind is a string value representing the REST resource this object represents.
            Servers may infer this from the endpoint the client submits requests to.
            Cannot be updated.
            In CamelCase.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
          type: string
        metadata:
          type: object
        templateRef:
          description: TemplateRef specifies the APIServiceExportTemplate to bind
            to.
          properties:
            name:
              description: name is the name of the APIServiceExportTemplate to bind
                to.
              type: string
          required:
          - name
          type: object
      required:
      - clusterIdentity
      - templateRef
      type: object
    served: true
    storage: true
    subresources: {}
