apiVersion: mysql.sql.m.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: mysql-cfg
  namespace: default
spec:
  credentials:
    source: MySQLConnectionSecret
    connectionSecretRef:
      name: db-conn
  tls: preferred
