apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-bind-embedded-user
rules:
- apiGroups: ["kube-bind.io"]
  resources: ["*"]
  verbs: ["bind"]
- nonResourceURLs: ["/", "/api", "/api/*", "/apis", "/apis/*"]
  verbs: ["access"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-bind-embedded-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-bind-embedded-user
subjects:
- kind: User
  name: kube-bind-embedded-user
  apiGroup: rbac.authorization.k8s.io